# Generated by Django 5.2.6 on 2025-10-05 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MajorUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_link', models.CharField(blank=True, max_length=200)),
                ('stock_number', models.CharField(max_length=50)),
                ('mfg', models.CharField(max_length=50)),
                ('year', models.CharField(max_length=10)),
                ('model_name', models.CharField(max_length=200)),
                ('store', models.CharField(blank=True, max_length=50)),
                ('quote_level', models.CharField(blank=True, max_length=10)),
                ('msrp_total', models.CharField(blank=True, max_length=20)),
                ('sale_price', models.CharField(blank=True, max_length=20)),
                ('nap', models.CharField(blank=True, max_length=20)),
                ('profit_margin', models.CharField(blank=True, max_length=20)),
                ('brochure', models.CharField(blank=True, max_length=20)),
                ('new_edit_modal', models.CharField(blank=True, max_length=20)),
                ('website_price', models.CharField(blank=True, max_length=20)),
                ('cycle_trader', models.CharField(blank=True, max_length=20)),
                ('location_status', models.CharField(blank=True, max_length=20)),
                ('program', models.CharField(blank=True, max_length=20)),
                ('days_on_floor', models.CharField(blank=True, max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Major Unit',
                'verbose_name_plural': 'Major Units',
                'ordering': ['-created_at'],
            },
        ),
    ]
